[auth]
redirect_uri_local="http://localhost:8501/oauth2callback"
redirect_uri ="https://cmch-upchic2.streamlit.app/oauth2callback"
cookie_secret="e1f4c8b7a3d9f2e6c5b1a7e8d3f6c2b9e7a4d1c6b8f3e2a5c9b7d4e1f8a6c3b2"

[auth.google]
domain = "dev-ccu3q85vkllkzvbh.us.auth0.com"
client_id="5k7shuWb4WjE5TxpW1r6PkBuoLBG8UFn"
client_secret="5k7shuWb4WjE5TxpW1r6PkBuoLBG8UFn"
server_metadata_url="https://dev-ccu3q85vkllkzvbh.us.auth0.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }